# Generated by Django 2.2.8 on 2020-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_admin", "0002_externalplugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalplugin",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="externalplugin",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="externalplugin",
            name="version",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
