# Generated by Django 2.2.8 on 2020-04-05 11:58

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services_admin", "0003_auto_20200402_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalplugin",
            name="keywords",
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
